### PR TITLE
Pdfs improvement

### PR DESCRIPTION
**Pull request by fxbabin**

### CODE REVIEW

**Comment by matboivin** [comment]
- Day00: page 10, is the quote formatted this way on purpose?
- Day01: last page can be removed.
- Day04: pages 8-9 weirdly splitted but it is automatically done this way.

Good job! Thank you! :smile:

**Comment by fxbabin** [comment]
Day00 the quote is in a code block (the person who putted the quote did that)
Day01 i cannot remove the last page without forcing the last block on the last page. i don't know why pandoc has this behaviour 
Day04 it's a normal behaviour even if the split is strange

**Review by matboivin — APPROVED** [review]

**Comment by matboivin** [comment]
I will maybe remove a la mano the last page for day01 before merge to master.
Thanks for your useful work! :smile:

**Review by ppeigne — APPROVED** [review]
All good to me :)

**Pull request merged**
